### ISSUE TITLE
cpuctl directory doesnt exist on the system

### ISSUE THREAD

**Issue by error404-personnotfound** [servalproject/batphone#133] opened 2017-11-05 06:02 UTC
Error while monitoring the working of app through terminal.

fopen failed: /dev/cpuctl/ux/tasks, Permission denied

How to reslove this error

**Comment by lakeman** [comment] 2017-11-05 09:03
I can't help you if you don't provide any context about what you are doing.

**Comment by lakeman** [comment] 2017-11-05 09:05
Also, this is a duplicate of #132

**Closed as completed by lakeman** 2017-11-05 09:05 UTC
